Algoritmo "lista_1_exercicio_11"

Var

   nota_1, nota_2, nota_3: real
   media: real

Inicio

      escreval("Forneça três notas para calcularmos a média ")
      escreval("Digite a primeira nota")
      leia(nota_1)
      escreval("Digite a segunda nota")
      leia(nota_2)
      escreval("Digite a terceira nota")
      leia(nota_3)
      
      escreval("")
      escreval("O valor da média é ", (nota_1 + nota_2 + nota_3) / 3)



Fimalgoritmo