Algoritmo "lista_1_exercicio_6"

Var

   raio, volume, altura: real

Inicio

      escreval("Vamos calcular o volume do cilindro ")
      escreval("Digite o raio do cilindro ")
      leia(raio)
      escreval("Digite a altura do cilindro ")
      leia(altura)
      
      volume <- (3.1416 * (raio * raio)) * altura
      
      
      escreval("")
      escreval("O valor calculado para o volume do cilindro é: ", volume)
      
      



Fimalgoritmo