Algoritmo "lista_1_exercicio_15"

Var

   valor_1, valor_2: real

Inicio

      escreval("Forneça dois numeros para calcularmos a 10ª parte da subtração (usando duas variaveis)")
      escreval("Digite o primeiro numero ")
      leia(valor_1)
      escreval("Digite o primeiro numero ")
      leia(valor_2)

      escreval("")
      escreval("O valor da 10ª parte é ", (valor_1 - valor_2) / 10)



Fimalgoritmo