Algoritmo "lista_1_exercicio_2"

Var

   numero_1, numero_2: real
   soma: real


Inicio

      escreval("Vamos realizar a soma de dois numeros")
      escreval("Digite o primeiro numero ")
      leia(numero_1)
      escreval("Digite o segundo numero ")
      leia(numero_2)
      
      soma <- numero_1 + numero_2
      
      escreval("")
      escreval("A soma desses numeros é igual a: ", soma)


Fimalgoritmo