Algoritmo "lista_1_exercicio_12"

Var

   valor_1, valor_2, valor_3: real

Inicio

      escreval("Forneça três numeros para calcularmos a multiplicação deles ")
      escreval("Digite o primeiro numero ")
      leia(valor_1)
      escreval("Digite o primeiro numero ")
      leia(valor_2)
      escreval("Digite o primeiro numero ")
      leia(valor_3)

      escreval("")
      escreval("O valor da multiplicação é ", valor_1 * valor_2 * valor_3)



Fimalgoritmo