Algoritmo "lista_1_exercicio_14"

Var

   valor_1, valor_2, decima_parte: real

Inicio

      escreval("Forneça dois numeros para calcularmos a 10ª parte da subtração ")
      escreval("Digite o primeiro numero ")
      leia(valor_1)
      escreval("Digite o primeiro numero ")
      leia(valor_2)
      
      decima_parte <- (valor_1 - valor_2) / 10

      escreval("")
      escreval("O valor da 10ª parte é ", decima_parte)



Fimalgoritmo