Algoritmo "lista_1_exercicio_8"

Var

   lado, altura: real
   volume: real

Inicio

      escreval("Vamos calcular o volume da piramide ")
      escreval("Digite o lado da piramide ")
      leia(lado)
      escreval("Digite a altura da piramide ")
      leia(altura)

      volume <- (lado * lado) * (altura / 3)

      escreval("")
      escreval("O valor calculado para o volume da piramide é: ", volume)





Fimalgoritmo