Algoritmo "lista_2_exerc_1"

Var

   nome: caracter
   idade: inteiro

Inicio

      escreval("Digite seu nome")
      leia(nome)
      escreval("Digite sua idade")
      leia(idade)
      
      escreval("")

      se ( idade >= 18) entao
         escreval ("Você já pode tirar sua CNH!")
      senao
           escreval ("Você deve ter 18 anos para tirar CNH")
      fimse
      



Fimalgoritmo