Algoritmo "lista_2_exerc_19"

Var

   num1, num2: real

Inicio

      escreval("Digite 1º numero")
      leia(num1)
      escreval("Digite 2º numero")
      leia(num2)
      
      se num1 > num2 entao
         escreval("O maior subtraido pelo menor é: ", num1 - num2)
         senao
              escreval("O maior subtraido pelo menor é: ", num2 - num1)
      fimse



Fimalgoritmo